on:
  push:
    branches: [deploy]

# Allow one concurrent deployment
concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install direnv libvips
          pkg-config --modversion vips-cpp
          direnv allow
      - name: Deploy
        run: |
          direnv exec bin/blog deploy
        env:
          XMIT_KEY: ${{ secrets.XMIT_KEY }}
